"""ETF holdings fetcher for generating watchlists from ETF constituents."""

import asyncio
import logging
from typing import Any

import yfinance as yf

from stockstalk.models import WatchlistItem

logger = logging.getLogger(__name__)

# Default indicators to apply to all VTI stocks
DEFAULT_VTI_INDICATORS = [
    "RSI",
    "MACD",
    "Volume_Spike",  # Volume spikes are critical for catching momentum
    "Price_Change",
]


class ETFHoldingsFetcher:
    """Fetches ETF holdings and generates watchlist items."""

    def __init__(self, etf_symbol: str = "VTI") -> None:
        """
        Initialize the ETF holdings fetcher.

        Args:
            etf_symbol: The ETF ticker symbol (default: VTI)
        """
        self.etf_symbol = etf_symbol.upper()

    def _fetch_holdings_sync(self) -> list[dict[str, Any]]:
        """
        Synchronously fetch ETF holdings from Yahoo Finance.

        Returns:
            List of holding dictionaries with symbol and weight
        """
        try:
            ticker = yf.Ticker(self.etf_symbol)

            # Try to get holdings from the ETF
            # yfinance provides holdings via the 'funds_data' property for ETFs
            try:
                holdings_df = ticker.funds_data.top_holdings
                if holdings_df is not None and not holdings_df.empty:
                    holdings = []
                    for symbol, row in holdings_df.iterrows():
                        # Symbol is the index, weight is in the 'holdingPercent' column
                        if isinstance(symbol, str) and symbol:
                            weight = row.get("holdingPercent", row.iloc[0]) if len(row) > 0 else 0
                            holdings.append(
                                {
                                    "symbol": symbol.upper(),
                                    "weight": float(weight) if weight else 0,
                                }
                            )
                    return holdings
            except Exception as e:
                logger.debug(f"Could not fetch holdings via funds_data: {e}")

            # Fallback: Try the info dict
            info = ticker.info
            if "holdings" in info:
                return [
                    {
                        "symbol": h.get("symbol", "").upper(),
                        "weight": h.get("holdingPercent", 0),
                    }
                    for h in info["holdings"]
                    if h.get("symbol")
                ]

            logger.warning(
                f"Could not fetch live holdings for {self.etf_symbol}. "
                "Using curated VTI top holdings list."
            )
            return self._get_curated_vti_holdings()

        except Exception as e:
            logger.error(f"Error fetching {self.etf_symbol} holdings: {e}")
            return self._get_curated_vti_holdings()

    def _get_curated_vti_holdings(self) -> list[dict[str, Any]]:
        """
        Return a curated list of VTI's top ~1000 holdings by market cap.

        This is a fallback when live data isn't available.
        Data sourced from Vanguard's VTI holdings as of late 2024.
        """
        # Top 1000 VTI holdings by market cap (curated list)
        # This includes the largest US stocks that make up the bulk of VTI
        top_holdings = [
            # Mega-cap tech (Top 10)
            "AAPL",
            "MSFT",
            "NVDA",
            "GOOGL",
            "GOOG",
            "AMZN",
            "META",
            "BRK-B",
            "LLY",
            "AVGO",
            # Top 11-50
            "JPM",
            "TSLA",
            "V",
            "UNH",
            "XOM",
            "MA",
            "JNJ",
            "COST",
            "HD",
            "PG",
            "MRK",
            "ABBV",
            "WMT",
            "NFLX",
            "CVX",
            "BAC",
            "CRM",
            "KO",
            "PEP",
            "AMD",
            "ORCL",
            "TMO",
            "ADBE",
            "ACN",
            "WFC",
            "MCD",
            "CSCO",
            "LIN",
            "ABT",
            "PM",
            # Top 51-100
            "NOW",
            "GE",
            "QCOM",
            "DHR",
            "ISRG",
            "DIS",
            "INTU",
            "TXN",
            "CMCSA",
            "CAT",
            "IBM",
            "AMGN",
            "VZ",
            "AMAT",
            "GS",
            "PFE",
            "AXP",
            "MS",
            "BX",
            "NEE",
            "SPGI",
            "T",
            "UBER",
            "RTX",
            "HON",
            "LOW",
            "BKNG",
            "ETN",
            "SYK",
            "UNP",
            "COP",
            "PGR",
            "BLK",
            "LRCX",
            "ELV",
            "TJX",
            "C",
            "SCHW",
            "VRTX",
            "PANW",
            # Top 101-200
            "BSX",
            "MDT",
            "ADI",
            "REGN",
            "MMC",
            "MU",
            "DE",
            "ADP",
            "CB",
            "SBUX",
            "FI",
            "GILD",
            "CI",
            "ANET",
            "KKR",
            "BMY",
            "SO",
            "KLAC",
            "TMUS",
            "ICE",
            "CME",
            "PLD",
            "SHW",
            "DUK",
            "INTC",
            "MO",
            "MDLZ",
            "PYPL",
            "CEG",
            "SNPS",
            "MCO",
            "AON",
            "APH",
            "EQIX",
            "MCK",
            "WELL",
            "APO",
            "ZTS",
            "WM",
            "MSI",
            "EMR",
            "GD",
            "ITW",
            "PH",
            "CRWD",
            "USB",
            "CL",
            "CDNS",
            "CMG",
            "TT",
            "ORLY",
            "PNC",
            "NOC",
            "MAR",
            "TGT",
            "MMM",
            "CTAS",
            "CARR",
            "COF",
            "ECL",
            "CVS",
            "AJG",
            "NXPI",
            "EOG",
            "HLT",
            "FDX",
            "AZO",
            "ROP",
            "NSC",
            "AFL",
            "PSA",
            "TDG",
            "SPG",
            "BDX",
            "FTNT",
            "SLB",
            "HCA",
            "ABNB",
            "FCX",
            "RCL",
            "AIG",
            "WMB",
            "JCI",
            "NEM",
            "TFC",
            "MPC",
            "DLR",
            "OXY",
            "SRE",
            "PCAR",
            "GM",
            "AMP",
            "FICO",
            "CPRT",
            "PSX",
            "MET",
            "AEP",
            "VLO",
            "ALL",
            "MNST",
            # Top 201-300
            "O",
            "D",
            "DHI",
            "PAYX",
            "KMB",
            "MSCI",
            "ROST",
            "BK",
            "TEL",
            "HUM",
            "GWW",
            "LHX",
            "MCHP",
            "FAST",
            "PRU",
            "KVUE",
            "PEG",
            "CTVA",
            "AME",
            "RSG",
            "LEN",
            "CNC",
            "VRSK",
            "F",
            "CMI",
            "A",
            "EW",
            "PCG",
            "OKE",
            "IQV",
            "PWR",
            "IDXX",
            "ODFL",
            "HES",
            "KMI",
            "CTSH",
            "EXC",
            "GEHC",
            "EA",
            "ACGL",
            "XEL",
            "IR",
            "YUM",
            "KDP",
            "OTIS",
            "GIS",
            "URI",
            "IT",
            "DD",
            "HSY",
            "MLM",
            "LULU",
            "ON",
            "EXR",
            "ED",
            "ROK",
            "KR",
            "SYY",
            "CSGP",
            "RMD",
            "AXON",
            "DXCM",
            "HWM",
            "VMC",
            "DOV",
            "DAL",
            "FANG",
            "EIX",
            "WEC",
            "VICI",
            "ANSS",
            "HPQ",
            "NVR",
            "GRMN",
            "EL",
            "HAL",
            "DFS",
            "BIIB",
            "TTWO",
            "MTD",
            "KEYS",
            "MTB",
            "FITB",
            "TSCO",
            "PPG",
            "EBAY",
            "AVB",
            "BRO",
            "WAB",
            "GPN",
            "TROW",
            "PHM",
            "CHD",
            "WTW",
            "STZ",
            "AWK",
            "NUE",
            "DOW",
            "EFX",
            "VLTO",
            # Top 301-400
            "CHTR",
            "DECK",
            "WDC",
            "CDW",
            "HUBB",
            "SBAC",
            "HBAN",
            "XYL",
            "TYL",
            "ETR",
            "CAH",
            "FTV",
            "BR",
            "GLW",
            "ROL",
            "IRM",
            "NTAP",
            "WST",
            "ZBH",
            "ES",
            "DTE",
            "PPL",
            "FE",
            "STLD",
            "IFF",
            "INVH",
            "BALL",
            "LDOS",
            "CBRE",
            "WRB",
            "RF",
            "CINF",
            "LYB",
            "TER",
            "ARE",
            "CLX",
            "TSN",
            "WAT",
            "EXPE",
            "AEE",
            "CNP",
            "ZBRA",
            "EQR",
            "STT",
            "K",
            "ULTA",
            "TRGP",
            "DRI",
            "ALGN",
            "MOH",
            "PKG",
            "J",
            "PFG",
            "STE",
            "MAA",
            "CCL",
            "HOLX",
            "NTRS",
            "LYV",
            "LUV",
            "TDY",
            "IP",
            "AMCR",
            "AKAM",
            "MAS",
            "PODD",
            "LH",
            "GPC",
            "VTR",
            "CMS",
            "DLTR",
            "BAX",
            "EG",
            "CBOE",
            "MKC",
            "CTRA",
            "COO",
            "EXPD",
            "WY",
            "HPE",
            "DGX",
            "FDS",
            "JBHT",
            "NI",
            "BBY",
            "CF",
            "KEY",
            "SWK",
            "POOL",
            "PTC",
            "AVY",
            "NDAQ",
            "IEX",
            "EVRG",
            "DOC",
            "TXT",
            "BLDR",
            "CPT",
            "DG",
            "RVTY",
            # Top 401-500
            "KIM",
            "UDR",
            "APTV",
            "SNA",
            "ESS",
            "PEAK",
            "EMN",
            "WBA",
            "HST",
            "TAP",
            "L",
            "BXP",
            "SJM",
            "RL",
            "TPR",
            "JNPR",
            "PARA",
            "AAL",
            "BG",
            "ALB",
            "BWA",
            "AOS",
            "AIZ",
            "ALLE",
            "FMC",
            "UHS",
            "MOS",
            "RHI",
            "HII",
            "CRL",
            "DVA",
            "NWS",
            "NWSA",
            "BEN",
            "SEE",
            "CE",
            "HRL",
            "WYNN",
            "FRT",
            "GNRC",
            "FFIV",
            "CHRW",
            "CZR",
            "PNR",
            "REG",
            "APA",
            "MKTX",
            "VFC",
            "MTCH",
            "TECH",
            "DVN",
            "IPG",
            "IVZ",
            "HSIC",
            "PNW",
            "NCLH",
            "WRK",
            "GL",
            "AAP",
            "ETSY",
            "CAG",
            "CMA",
            "MGM",
            "NRG",
            "PAYC",
            "CPB",
            "MHK",
            "OMC",
            "WHR",
            "ZION",
            "CTLT",
            "INCY",
            "DISH",
            "BBWI",
            "XRAY",
            "LNC",
            "LUMN",
            "FLS",
            "ALK",
            "FOXA",
            "FOX",
            "OGN",
            "NDSN",
            "HAS",
            "ATO",
            "EPAM",
            "VTRS",
            "LW",
            "ENPH",
            "TFX",
            "RNR",
            "LKQ",
            "QRVO",
            "JKHY",
            "MRNA",
            "SWKS",
            "WDAY",
            "SEDG",
            "PAYC",
            "RJF",
            # Top 501-600
            "ILMN",
            "BMRN",
            "EXAS",
            "SGEN",
            "MELI",
            "TEAM",
            "DDOG",
            "ZS",
            "NET",
            "COIN",
            "OKTA",
            "MDB",
            "SNOW",
            "SPLK",
            "SHOP",
            "SQ",
            "ROKU",
            "PINS",
            "SNAP",
            "RBLX",
            "DASH",
            "ABNB",
            "HOOD",
            "RIVN",
            "LCID",
            "PLTR",
            "PATH",
            "CFLT",
            "BILL",
            "DOCN",
            "ESTC",
            "GTLB",
            "MNDY",
            "FROG",
            "SUMO",
            "NEWR",
            "JAMF",
            "SMAR",
            "ZI",
            "BRZE",
            "PCTY",
            "APPN",
            "COUP",
            "NCNO",
            "SPSC",
            "TENB",
            "CWST",
            "QTWO",
            "EVER",
            "ALTR",
            "MGNI",
            "PUBM",
            "CRTO",
            "TTD",
            "DV",
            "APPS",
            "PRPL",
            "ENVX",
            "CHPT",
            "BLNK",
            "EVGO",
            "QS",
            "ARRY",
            "RUN",
            "NOVA",
            "MAXN",
            "FSLR",
            "SPWR",
            "PLUG",
            "BLDP",
            "BE",
            "FCEL",
            "CLSK",
            "RIOT",
            "MARA",
            "HUT",
            "BTBT",
            "BITF",
            "CIFR",
            "GREE",
            "EBON",
            "CAN",
            "HIVE",
            "IREN",
            "WULF",
            "CORZ",
            "SDIG",
            "BTDR",
            "SOS",
            "EQOS",
            "ARBK",
            "NCTY",
            "DMYQ",
            "SLNH",
            "DGII",
            "CALX",
            "VIAV",
            "LITE",
            "COHU",
            "ACLS",
            # Top 601-700
            "AEHR",
            "CRUS",
            "POWI",
            "DIOD",
            "SLAB",
            "SMTC",
            "RMBS",
            "AMBA",
            "NXGN",
            "PDFS",
            "MKSI",
            "FORM",
            "ONTO",
            "CGNX",
            "NOVT",
            "MASI",
            "HAYW",
            "VRNS",
            "INST",
            "MATW",
            "NVMI",
            "ICHR",
            "PLAB",
            "CCMP",
            "UCTT",
            "PCT",
            "PRFT",
            "VICR",
            "ASGN",
            "EXTR",
            "NSIT",
            "VRNT",
            "GDYN",
            "GIB",
            "CLVT",
            "TWOU",
            "CHGG",
            "CSOD",
            "FRSH",
            "PRGS",
            "MANH",
            "NICE",
            "TOST",
            "CPNG",
            "DUOL",
            "COUR",
            "UDMY",
            "UPST",
            "AFRM",
            "SOFI",
            "LC",
            "OPEN",
            "RDFN",
            "COMP",
            "ZG",
            "Z",
            "REAL",
            "EXPI",
            "RMAX",
            "RLGY",
            "CVNA",
            "CARG",
            "KMX",
            "GPI",
            "AN",
            "PAG",
            "ABG",
            "SAH",
            "SBH",
            "LAD",
            "ORLY",
            "AZO",
            "AAP",
            "GPC",
            "LKQ",
            "MNRO",
            "PRTS",
            "MOD",
            "DORM",
            "PATK",
            "LCII",
            "WGO",
            "THO",
            "CWH",
            "BC",
            "REVG",
            "OSK",
            "TTC",
            "AGCO",
            "CNHI",
            "DE",
            "CAT",
            "PCAR",
            "CMI",
            "NAV",
            "ALV",
            "ALSN",
            "DAN",
            "ADNT",
            "LEA",
            # Top 701-800
            "BWA",
            "AXL",
            "VC",
            "APTV",
            "GNTX",
            "MTOR",
            "SUP",
            "SMP",
            "DORM",
            "SRI",
            "CPS",
            "GTX",
            "MOD",
            "PII",
            "HOG",
            "FOXF",
            "MPAA",
            "TORC",
            "RIDE",
            "FSR",
            "NKLA",
            "GOEV",
            "ARVL",
            "REE",
            "FFIE",
            "EVEX",
            "PTRA",
            "XL",
            "HYLN",
            "WORX",
            "SHYF",
            "HCIC",
            "SEA",
            "GRAB",
            "GOTU",
            "TAL",
            "EDU",
            "LSPD",
            "BILL",
            "FIVN",
            "RNG",
            "TWLO",
            "ZEN",
            "HUBS",
            "AYX",
            "CLDR",
            "NEOG",
            "BLKB",
            "PLAN",
            "DOMO",
            "EVBG",
            "ALRM",
            "RPD",
            "SCWX",
            "CYBR",
            "VRNS",
            "SAIL",
            "CWAN",
            "PD",
            "BASE",
            "AI",
            "BIGC",
            "DCBO",
            "WEAV",
            "INFA",
            "CERT",
            "PRFT",
            "INTA",
            "PYCR",
            "GENI",
            "MGNI",
            "PERI",
            "QNST",
            "STCN",
            "SSTK",
            "JFROG",
            "CWAN",
            "NCNO",
            "APPN",
            "PCTY",
            "PAYC",
            "PAYX",
            "PAYR",
            "ADP",
            "SPSC",
            "CASS",
            "ACIW",
            "PRTH",
            "RELY",
            "BTRS",
            "FISV",
            "FI",
            "GPN",
            "FOUR",
            "RPAY",
            "PAYO",
            "KSPI",
            "NU",
            "STNE",
            "PAGS",
            # Top 801-900
            "DLO",
            "AFYA",
            "VTRU",
            "ARCO",
            "MELI",
            "GLBE",
            "GLOB",
            "DOCN",
            "DAVA",
            "UPWK",
            "FVRR",
            "TASK",
            "KFRC",
            "HURN",
            "ICFI",
            "EXPO",
            "LSCC",
            "MTSI",
            "LFUS",
            "SGH",
            "HIMX",
            "PRIM",
            "MPWR",
            "SWKS",
            "QRVO",
            "CEVA",
            "SITM",
            "VLDR",
            "OUST",
            "LAZR",
            "INVZ",
            "AEVA",
            "CPTN",
            "MVIS",
            "AAOI",
            "IIVI",
            "LITE",
            "CIEN",
            "VIAV",
            "FNSR",
            "PI",
            "CRNC",
            "OLED",
            "KOPN",
            "DXYN",
            "KOPIN",
            "VUZI",
            "IMMR",
            "EMAN",
            "LCOS",
            "MLED",
            "SMFL",
            "FMTX",
            "AUMN",
            "SSYS",
            "DDD",
            "MTLS",
            "XONE",
            "DM",
            "NNDM",
            "VJET",
            "PRLB",
            "BFLY",
            "ISRG",
            "MASI",
            "GMED",
            "NUVA",
            "KIDS",
            "ITGR",
            "HAE",
            "LMAT",
            "CRY",
            "ATRC",
            "NVRO",
            "ANIK",
            "SPNE",
            "BONE",
            "SIBN",
            "STAA",
            "NVCR",
            "ICUI",
            "PDCO",
            "XRAY",
            "ALGN",
            "SYK",
            "ZBH",
            "HOLX",
            "ILMN",
            "A",
            "DHR",
            "TMO",
            "WAT",
            "PKI",
            "MTD",
            "TECH",
            "BIO",
            "RGEN",
            "AZTA",
            "QGEN",
            "NEO",
            # Top 901-1000
            "NVTA",
            "CDNA",
            "TXG",
            "VCYT",
            "EXAS",
            "GH",
            "SDGR",
            "RXRX",
            "TWST",
            "DNA",
            "CDXS",
            "SGMO",
            "CRSP",
            "NTLA",
            "EDIT",
            "BEAM",
            "VERV",
            "BLUE",
            "SAGE",
            "IONS",
            "ALNY",
            "BMRN",
            "VRTX",
            "INCY",
            "RARE",
            "ALKS",
            "UTHR",
            "NBIX",
            "SRPT",
            "EXEL",
            "FOLD",
            "MDGL",
            "PTCT",
            "IMVT",
            "TGTX",
            "LEGN",
            "PCVX",
            "KRYS",
            "RCKT",
            "RLAY",
            "RPTX",
            "RVMD",
            "RCUS",
            "ANAB",
            "BCYC",
            "IGMS",
            "MGNX",
            "FATE",
            "ALLO",
            "CRISPR",
            "NTLA",
            "EDIT",
            "VERV",
            "BEAM",
            "CRSP",
            "CLLS",
            "KRON",
            "KALA",
            "OCUL",
            "ADPT",
            "RXDX",
            "ACAD",
            "ARVN",
            "TPTX",
            "NUVB",
            "MYOV",
            "BGNE",
            "ZLAB",
            "LEGN",
            "BNTX",
            "MRNA",
            "NVAX",
            "BNTX",
            "PFE",
            "JNJ",
            "MRK",
            "ABBV",
            "LLY",
            "BMY",
            "GILD",
            "AMGN",
            "REGN",
            "VRTX",
            "BIIB",
            "ALNY",
            "SGEN",
            "JAZZ",
            "HZNP",
            "RPRX",
            "MEDP",
            "ICLR",
            "CTLT",
            "WST",
            "CRL",
            "IQVIA",
            "PPD",
            "SYNH",
            "DOCS",
            "LHCG",
            "AMED",
        ]

        # Return as list of dicts with approximate weights (decreasing)
        holdings = []
        for i, symbol in enumerate(top_holdings):
            # Approximate weight - top stocks have higher weight
            weight = max(0.01, 10.0 / (i + 1))  # Decreasing weight
            holdings.append({"symbol": symbol, "weight": weight})

        return holdings

    async def fetch_holdings(self, top_n: int = 1000) -> list[dict[str, Any]]:
        """
        Asynchronously fetch ETF holdings.

        Args:
            top_n: Number of top holdings to return

        Returns:
            List of holding dictionaries sorted by weight
        """
        holdings = await asyncio.to_thread(self._fetch_holdings_sync)

        # Sort by weight descending and take top N
        holdings.sort(key=lambda x: x.get("weight", 0), reverse=True)
        return holdings[:top_n]

    async def generate_watchlist(
        self,
        top_n: int = 1000,
        indicators: list[str] | None = None,
        include_volume_spike: bool = True,
    ) -> list[WatchlistItem]:
        """
        Generate a watchlist from ETF holdings.

        Args:
            top_n: Number of top holdings to include
            indicators: List of indicators to enable (defaults to Volume_Spike focused set)
            include_volume_spike: Ensure Volume_Spike is always included

        Returns:
            List of WatchlistItem objects
        """
        if indicators is None:
            indicators = DEFAULT_VTI_INDICATORS.copy()
        elif include_volume_spike and "Volume_Spike" not in indicators:
            indicators = ["Volume_Spike"] + list(indicators)

        holdings = await self.fetch_holdings(top_n)

        # Remove duplicates while preserving order
        seen = set()
        unique_holdings = []
        for h in holdings:
            symbol = h["symbol"]
            if symbol not in seen:
                seen.add(symbol)
                unique_holdings.append(h)

        watchlist = []
        for holding in unique_holdings:
            symbol = holding["symbol"]

            # Skip problematic symbols
            if not symbol or len(symbol) > 10:
                continue

            # For top 50 holdings, add more comprehensive analysis
            if len(watchlist) < 50:
                stock_indicators = indicators + ["Fundamental_Score"]
            else:
                stock_indicators = indicators.copy()

            watchlist.append(
                WatchlistItem(
                    symbol=symbol,
                    enabled_indicators=list(set(stock_indicators)),  # Remove duplicates
                    custom_params={},
                )
            )

        logger.info(f"Generated watchlist with {len(watchlist)} stocks from {self.etf_symbol}")
        return watchlist
