"""Base indicator class and types for the extensible indicator system."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict

from stock_sentinel.data.models import StockData


class SignalType(str, Enum):
    """Type of trading signal generated by an indicator."""

    STRONG_BUY = "strong_buy"
    BUY = "buy"
    NEUTRAL = "neutral"
    SELL = "sell"
    STRONG_SELL = "strong_sell"

    @property
    def is_bullish(self) -> bool:
        """Check if signal is bullish."""
        return self in (SignalType.STRONG_BUY, SignalType.BUY)

    @property
    def is_bearish(self) -> bool:
        """Check if signal is bearish."""
        return self in (SignalType.STRONG_SELL, SignalType.SELL)

    @property
    def emoji(self) -> str:
        """Get emoji representation of signal."""
        return {
            SignalType.STRONG_BUY: "🚀",
            SignalType.BUY: "📈",
            SignalType.NEUTRAL: "➡️",
            SignalType.SELL: "📉",
            SignalType.STRONG_SELL: "🔻",
        }[self]


class IndicatorResult(BaseModel):
    """Result from an indicator analysis."""

    model_config = ConfigDict(frozen=True)

    indicator_name: str
    symbol: str
    signal: SignalType
    value: float
    message: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)
    should_alert: bool = False

    @property
    def alert_message(self) -> str:
        """Format message for SMS alert."""
        return f"{self.signal.emoji} {self.symbol}: {self.message} [{self.indicator_name}]"


@dataclass
class IndicatorConfig:
    """Configuration for an indicator."""

    enabled: bool = True
    alert_on_buy: bool = True
    alert_on_sell: bool = False
    custom_params: dict[str, Any] = field(default_factory=dict)


class Indicator(ABC):
    """
    Abstract base class for all stock indicators.

    To create a new indicator:
    1. Subclass this class
    2. Implement the `name`, `description`, and `analyze` methods
    3. Register with the indicator registry using @indicator_registry.register

    Example:
        @indicator_registry.register
        class MyIndicator(Indicator):
            @property
            def name(self) -> str:
                return "my_indicator"

            @property
            def description(self) -> str:
                return "My custom indicator"

            async def analyze(self, stock_data: StockData) -> IndicatorResult:
                # Your analysis logic here
                ...
    """

    def __init__(self, config: IndicatorConfig | None = None):
        """Initialize indicator with optional configuration."""
        self.config = config or IndicatorConfig()

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique identifier for this indicator."""
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of what this indicator does."""
        ...

    @property
    def required_history_days(self) -> int:
        """Minimum number of days of history required for this indicator."""
        return 20  # Default, override if needed

    @abstractmethod
    async def analyze(self, stock_data: StockData) -> IndicatorResult | None:
        """
        Analyze stock data and generate a trading signal.

        Args:
            stock_data: Complete stock data including history and current quote

        Returns:
            IndicatorResult with signal and analysis details, or None if
            insufficient data or no significant signal
        """
        ...

    def _create_result(
        self,
        symbol: str,
        signal: SignalType,
        value: float,
        message: str,
        should_alert: bool = False,
        **metadata: Any,
    ) -> IndicatorResult:
        """Helper to create an IndicatorResult."""
        # Determine if we should alert based on config
        alert = False
        if should_alert and (
            (signal.is_bullish and self.config.alert_on_buy)
            or (signal.is_bearish and self.config.alert_on_sell)
        ):
            alert = True

        return IndicatorResult(
            indicator_name=self.name,
            symbol=symbol,
            signal=signal,
            value=value,
            message=message,
            timestamp=datetime.now(),
            metadata=dict(metadata),
            should_alert=alert,
        )
